# Quieter logs
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

logging.level.io.github.thesmoothrere.revoicebot=DEBUG

spring.data.redis.username=${REDIS_USER}
spring.data.redis.password=${REDIS_PASSWORD}

# Bigger pool to handle more traffic
spring.datasource.hikari.maximum-pool-size=20