CREATE TABLE guilds (
                        id bigint GENERATED BY DEFAULT AS IDENTITY,
                        guild_id bigint NOT NULL,
                        premium boolean NOT NULL,
                        premium_started_at timestamp(6) WITH TIME ZONE,
                        premium_expires_at timestamp(6) WITH TIME ZONE,
                        deleted boolean NOT NULL,
                        created_at timestamp(6) WITH TIME ZONE,
                        PRIMARY KEY (id),
                        CONSTRAINT idx_guild_guild_id UNIQUE (guild_id)
);

CREATE TABLE parent_channels (
                                 id bigint GENERATED BY DEFAULT AS IDENTITY,
                                 guild_id bigint,
                                 channel_id bigint NOT NULL,
                                 prefix varchar(255) NOT NULL,
                                 deleted boolean NOT NULL,
                                 created_at timestamp(6) WITH TIME ZONE,
                                 PRIMARY KEY (id),
                                 CONSTRAINT idx_parent_channels_channel_id UNIQUE (channel_id)
);

CREATE TABLE child_channels (
                                id bigint GENERATED BY DEFAULT AS IDENTITY,
                                parent_channel_id bigint,
                                channel_id bigint,
                                owner_id bigint NOT NULL,
                                count integer NOT NULL,
                                deleted boolean NOT NULL,
                                created_at timestamp(6) WITH TIME ZONE,
                                PRIMARY KEY (id),
                                CONSTRAINT idx_child_channels_channel_id UNIQUE (channel_id)
);

CREATE INDEX idx_child_channel ON child_channels (parent_channel_id, count, deleted);
CREATE INDEX idx_parent_channel ON parent_channels (prefix, deleted);

ALTER TABLE IF EXISTS child_channels
    ADD CONSTRAINT FK9bqqubgx6ebpipg2rw2lt7mfc
        FOREIGN KEY (parent_channel_id) REFERENCES parent_channels;

ALTER TABLE IF EXISTS parent_channels
    ADD CONSTRAINT FK4tfxg15eh9v75honsr1h6nv12
        FOREIGN KEY (guild_id) REFERENCES guilds;